version: "3"

tasks:
  generate:
    aliases:
      - go
    desc: "Generate code from proto files"
    cmds:
      - protoc -I src/proto src/proto/**/*.proto --go_out=./src/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./src/gen/go/ --go-grpc_opt=paths=source_relative
  python:
    aliases:
      - py
    desc: "Generate code python"
    cmds:
      - uv run python -m grpc_tools.protoc -I=src/proto --python_out=./src/gen/python --grpc_python_out=./src/gen/python src/proto/**/*.proto
